### ISSUE TITLE
Unable to import file in dispatcher 

### ISSUE THREAD

**Issue by suryaveer5320129** [hackergram/sakhacabs#116]
![image](https://user-images.githubusercontent.com/39553877/50054520-c7185d00-0168-11e9-85fc-ea7a3fdac48e.png)

error code from console:

Error: Unclosed tag at 36 mustache.min.js:1:2860
Array(30) [ "Sl. No", "Date of booking received", "Booking date", "mode of booking", "Company name", "Client name", "Retail/ Corporate", "Pick up point", "drop address", "Reporting time", … ]

**Comment by arjunvenkatraman** [comment]
Note that the file you mentioned had over 3000 bookings. It now works and tells you what the problem with each of your entries is!
"booking_id": "<class 'mongoengine.errors.ValidationError'> ValidationError (Booking:None) (Invalid dictionary key name - keys may not contain \".\" or \"$\" characters: ['cust_meta'])",
