### ISSUE TITLE
There is a mismatch of timestamp in telegram-bot during check-in, check-out

### ISSUE THREAD

**Issue by suryaveer5320129** [hackergram/sakhacabs#119]

**Comment by suryaveer5320129** [comment]
There is a mismatch of timestamp in telegram-bot during check-in,  check-out

**Comment by arjunvenkatraman** [comment]
Please provide slightly less lazy comments!
Issue here is that the timestamp on the display of the saved location update is showing incorrectly. It is showing the UTC timestamp instead of the local timestamp as it should. Issue is fixed now.
