### ISSUE TITLE
Registered driver is unable to access bot interface in telegram.

### ISSUE THREAD

**Issue by suryaveer5320129** [hackergram/sakhacabs#20]
Registered driver is unable to access bot interface in telegram (@driversakhabot).
![screenshot from 2018-11-21 12-52-29](https://user-images.githubusercontent.com/39553877/48825162-95d88700-ed8c-11e8-88be-b05207929a87.png)

mobile number: 8368988155
telegram version 1.4.3

**Comment by arjunvenkatraman** [comment]
This appears to be an issue with the leading + sign on the phone number. Stripping it by default in the fix
