### ISSUE TITLE
[BUG]-Invalid requirement: 'mongoengine flask-mongoengine==0.9.5'

### ISSUE THREAD

**Issue by kirantpatil** [hackergram/sakhacabs#201]
**Describe the bug**
I am trying to install sakhacabs and it is halting with below message.

Invalid requirement: 'mongoengine flask-mongoengine==0.9.5'

**To Reproduce**
1. cd sakhacabs/
2. sudo -H pip install -r requirements.txt
3. See error
    Invalid requirement: 'mongoengine flask-mongoengine==0.9.5'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 82, in __init__
    req = Requirement(req)
  File "/usr/share/python-wheels/packaging-17.1-py2.py3-none-any.whl/packaging/requirements.py", line 97, in __init__
    requirement_string[e.loc:e.loc + 8]))
InvalidRequirement: Invalid requirement, parse error at "u'flask-mo'"

**Expected behavior**
Install should complete without error

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python: Python 2.7.15rc1
 - $ mongo --version
MongoDB shell version v4.0.5
git version: 3739429dd92b92d1b0ab120911a23d50bf03c412
OpenSSL version: OpenSSL 1.1.0g  2 Nov 2017
allocator: tcmalloc
modules: none
build environment:
    distmod: ubuntu1804
    distarch: x86_64
    target_arch: x86_64

**Comment by suryaveer5320129** [comment]
Thanks for reporting the bug :+1:  we are fixing it

**Comment by suryaveer5320129** [comment]
I am the writing the readme for for the sakhacabs configuration file, kindly tell me a way, how i can reach out to you
