### ISSUE TITLE
[FAQ]-sakhacabs-appdata

### ISSUE THREAD

**Issue by kirantpatil** [hackergram/sakhacabs#205]
Hi,

I have sent mail to gaursurya33@protonmail.com and listener@hackergram.org to share the sakhacabs-appdata as mentioned in the INSTALL file.

Thanks.

**Comment by arjunvenkatraman** [comment]
@suryaveer5320129  is working on a cleaned up version of the config files. Will share shortly!

**Comment by kirantpatil** [comment]
Received config files.
