### ISSUE TITLE
[BUG]-ValueError: numpy.ufunc has the wrong size, try recompiling

### ISSUE THREAD

**Issue by kirantpatil** [hackergram/sakhacabs#209]
**Describe the bug**
I followed sakhacabs [installation](https://github.com/hackergram/sakhacabs/blob/master/docs/INSTALL.md) steps and "python dispatcherapi.py" results in error.

**To Reproduce**
1. $ python dispatcherapi.py
2.  See error

> $ python dispatcherapi.py
> Traceback (most recent call last):
>   File "dispatcherapi.py", line 8, in <module>
>     from sakhacabs.api import *
>   File "/home/smitha/Documents/kiran/sakhacabs/sakhacabs/api.py", line 16, in <module>
>     from sakhacabs import xpal
>   File "/home/smitha/Documents/kiran/sakhacabs/sakhacabs/xpal.py", line 12, in <module>
>     import xetrapal
>   File "/opt/xetrapal/xetrapal/__init__.py", line 40, in <module>
>     from .Xetrapal import *
>   File "/opt/xetrapal/xetrapal/Xetrapal.py", line 7, in <module>
>     import twkarmas
>   File "/opt/xetrapal/xetrapal/twkarmas.py", line 9, in <module>
>     import pandas
>   File "/usr/local/lib/python2.7/dist-packages/pandas/__init__.py", line 7, in <module>
>     from pandas import hashtable, tslib, lib
>   File "pandas/src/numpy.pxd", line 865, in init pandas.hashtable (pandas/hashtable.c:38266)
> ValueError: numpy.ufunc has the wrong size, try recompiling
> 

**Expected behavior**
 Should run the dispatcher web app, I guess.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Python: 2.7.15rc1

**Comment by arjunvenkatraman** [comment]
Looks like an outdated dependency. 
Try ``` sudo -H pip install -U numpy pandas```
