### ISSUE TITLE
[Test Case] (Regression) Customer Document creation should fail with validation error if no mobile number is provided

### ISSUE THREAD

**Issue by arjunvenkatraman** [hackergram/sakhacabs#211]
1. From Command line
2. From API 
3. From Import Form
4. From Customer Edit form

**Comment by arjunvenkatraman** [comment]
dev tested @suryaveer5320129 pls verify

**Comment by suryaveer5320129** [comment]
Checked and is working fine

**Comment by suryaveer5320129** [comment]
Checked and is working fine in production server
