### ISSUE TITLE
[Test Case] Booking Status Change Events Change Linked Objects Correctly

### ISSUE THREAD

**Issue by arjunvenkatraman** [hackergram/sakhacabs#213]
1. Booking created
    1. Booking status = "new"

2. Booking assigned
    1. Booking status = "assigned"
    2. Assignment status = "new"
    3. DutySlip status = "new"
3. Booking cancelled
     1. If last Booking in Assignment, 
         - Assignment status = "cancelled"
     2. Booking status = "cancelled"

**Comment by suryaveer5320129** [comment]
Checked, and is working fine

**Comment by suryaveer5320129** [comment]
Checked and is working fine
