### ISSUE TITLE
[Test Case] Assignment Status Change Events Change Linked Objects Correctly

### ISSUE THREAD

**Issue by arjunvenkatraman** [hackergram/sakhacabs#217]
1. Assignment deleted
    1. Delete all associated DutySlips
    2. For each Booking in assignment -
        - If Booking status not = "cancelled"
            1. Booking status = "new"
            2. Booking assignment = None

2. Assignment cancelled
    1. For all associated DutySlips
         1. DutySlip status = "cancelled"
    2. For each Booking in assignment -
        1. If Booking status not = "cancelled"
            1. Booking status = "new"
            2. Booking assignment = None

**Comment by arjunvenkatraman** [comment]
dev tested @suryaveer5320129  pls verify

**Comment by suryaveer5320129** [comment]
Checked and is working fine
