### ISSUE TITLE
[Test Case] DutySlip Status Change Events Change Linked Objects Correctly

### ISSUE THREAD

**Issue by arjunvenkatraman** [hackergram/sakhacabs#218]
1. DutySlip opened
    1. Booking status = "open"
    2. Assignment status = "open"
    3. DutySlip status = "open"

2. DutySlip closed
    1. DutySlip status = "closed"

3. DutySlip deleted
    1. If last DutySlip in Assignment, delete Assignment

**Comment by arjunvenkatraman** [comment]
dev tested @suryaveer5320129 pls verify

**Comment by suryaveer5320129** [comment]
Checked and is working fine

**Comment by suryaveer5320129** [comment]
Checked and is working fine on local
