### ISSUE TITLE
[BUG]-OSError: [Errno 13] Permission denied: '/opt/sakhacabs-appdata/xetrapal-data/XpalSession-2019Jan02-104551'

### ISSUE THREAD

**Issue by kirantpatil** [hackergram/sakhacabs#223]
**Describe the bug**
I executed "python dispatcherapi.py" from the path "/home/smitha/Documents/kiran/sakhacabs" as normal user  as mentioned in [INSTALL](https://github.com/hackergram/sakhacabs/blob/master/docs/INSTALL.md) guide and it results to error.

**To Reproduce**
1. python dispatcherapi.py
2. See error

> 2019-01-02 10:45:51 Sakha Cabs Xetrapal-MainThread-[__init__] INFO : My name is Sakha Cabs Xetrapal
> 2019-01-02 10:45:51 Sakha Cabs Xetrapal-MainThread-[setup_disk] INFO : I already have a datapath at the location /opt/sakhacabs-appdata/xetrapal-data
> 2019-01-02 10:45:51 Sakha Cabs Xetrapal-MainThread-[start_session] INFO : Creating a new path for this session at /opt/sakhacabs-appdata/xetrapal-data/XpalSession-2019Jan02-104551
> Traceback (most recent call last):
>   File "dispatcherapi.py", line 8, in <module>
>     from sakhacabs.api import *
>   File "/home/smitha/Documents/kiran/sakhacabs/sakhacabs/api.py", line 16, in <module>
>     from sakhacabs import xpal
>   File "/home/smitha/Documents/kiran/sakhacabs/sakhacabs/xpal.py", line 16, in <module>
>     sakhacabsxpal=xetrapal.Xetrapal(configfile="/opt/sakhacabs-appdata/sakhacabsxpal.conf")
>   File "/opt/xetrapal/xetrapal/Xetrapal.py", line 21, in __init__
>     super(Xetrapal,self).__init__(*args, **kwargs)
>   File "/opt/xetrapal/xetrapal/jeeva.py", line 31, in __init__
>     self.start_session()
>   File "/opt/xetrapal/xetrapal/jeeva.py", line 94, in start_session
>     os.mkdir(self.sessionpath)
> OSError: [Errno 13] Permission denied: '/opt/sakhacabs-appdata/xetrapal-data/XpalSession-2019Jan02-104551'
> 

**Expected behavior**
I think it should start the python web app

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Version: Python 2.7.15rc1

**Comment by kirantpatil** [comment]
No, I am executing it as normal user. It is not having write permissions to /opt/xxxx.

**Comment by arjunvenkatraman** [comment]
The user that is executing the dispatcher needs to have write access to /opt
The system is meant to run in a server/server container, not really on a desktop. 
Add the user to a group that has write access on ```/opt/sakhacabs-appdata```, or grant explicit rights. If this poses a security threat, please reference a best practice and will fix accordingly.
