### ISSUE TITLE
Getting many duty slips when net getting disconnected in the middle of the booking process.

### ISSUE THREAD

**Issue by karan100010** [hackergram/sakhacabs#23]
![bug2](https://user-images.githubusercontent.com/36842700/48836852-dbf01380-eda9-11e8-956d-b90802992432.jpg)

**Comment by arjunvenkatraman** [comment]
Did you click Save Assignment multiple times? 

TODO - Either close assignment modal on each save or clear selections or otherwise avoid duplicate assignments.
