### ISSUE TITLE
[FAQ]-The requested URL was not found on the server, http://0.0.0.0:5000/

### ISSUE THREAD

**Issue by kirantpatil** [hackergram/sakhacabs#251]
**Describe the bug**
I am running the app with below command sudo python dispatcherapi.py. Now I tried to access the app using http://0.0.0.0:5000 and it is giving 404 error

[Edit] What is correct URL to access the application ?
I tried with below URL as mentioned in "deploy.sh" file and none of them worked.

http://192.168.0.126:5000/dispatcher/index.html
http://192.168.0.126:5000/dispatcher/managebookings.html
http://192.168.0.126:5000/bookingweb/index.html

**To Reproduce**
1. sudo python dispatcherapi.py.
2. On browser provide URL http://0.0.0.0:5000 and hit enter
3. See error

> $ sudo python dispatcherapi.py
> [sudo] password for smitha: 
> 2019-01-03 14:19:43 Sakha Cabs Xetrapal-MainThread-[__init__] INFO : My name is Sakha Cabs Xetrapal
> 2019-01-03 14:19:43 Sakha Cabs Xetrapal-MainThread-[setup_disk] INFO : I already have a datapath at the location /opt/sakhacabs-appdata/xetrapal-data
> 2019-01-03 14:19:43 Sakha Cabs Xetrapal-MainThread-[start_session] INFO : Creating a new path for this session at /opt/sakhacabs-appdata/xetrapal-data/XpalSession-2019Jan03-141943
> 2019-01-03 14:19:44 Sakha Cabs Xetrapal-MainThread-[start_session] INFO : Creating a new download path for this session at /opt/sakhacabs-appdata/xetrapal-data/XpalSession-2019Jan03-141943/downloads
> 2019-01-03 14:19:44 Sakha Cabs Xetrapal-MainThread-[start_session] INFO : Creating a new json path for this session at /opt/sakhacabs-appdata/xetrapal-data/XpalSession-2019Jan03-141943/json 
> 2019-01-03 14:19:44 Sakha Cabs Xetrapal-MainThread-[log_to_disk] INFO : Saving messages to log at /opt/sakhacabs-appdata/xetrapal-data/XpalSession-2019Jan03-141943/jeevasession.log
> 2019-01-03 14:19:44 Sakha Cabs Xetrapal-MainThread-[save_profile] INFO : Saving own JSON profile to file /opt/sakhacabs-appdata/xetrapal-data/jeeva.json
> 2019-01-03 14:19:44 Sakha Cabs Xetrapal-MainThread-[update_astras] INFO : Trying to update astras
> 2019-01-03 14:19:44 Sakha Cabs Xetrapal-MainThread-[update_astras] WARNING : I dont seem to have any astras
> 2019-01-03 14:19:44 Sakha Cabs Xetrapal-MainThread-[save_profile] INFO : Saving own JSON profile to file /opt/sakhacabs-appdata/xetrapal-data/jeeva.json
> 2019-01-03 14:19:44 Sakha Cabs Xetrapal-MainThread-[update_vaahans] INFO : Trying to update vaahans
> 2019-01-03 14:19:44 Sakha Cabs Xetrapal-MainThread-[update_vaahans] WARNING : I dont seem to have any vaahans
> 2019-01-03 14:19:44 Sakha Cabs Xetrapal-MainThread-[save_profile] INFO : Saving own JSON profile to file /opt/sakhacabs-appdata/xetrapal-data/jeeva.json
> 2019-01-03 14:19:44 Sakha Cabs Xetrapal-MainThread-[save_profile] INFO : Saving own JSON profile to file /opt/sakhacabs-appdata/xetrapal-data/jeeva.json
> 2019-01-03 14:19:44 Sakha Cabs Xetrapal-MainThread-[get_googledriver] INFO : Trying to log into Google drive
> 2019-01-03 14:19:44 Sakha Cabs Xetrapal-MainThread-[get_googledriver] ERROR : Could not get google driver config because [Errno 2] Client secret file does not exist.: u'/opt/sakhacabs-appdata/xetrapal-auth/sakhacabsxpal.json'
> 2019-01-03 14:19:44 Sakha Cabs Xetrapal-MainThread-[update_astras] INFO : Trying to update astras
> 2019-01-03 14:19:44 Sakha Cabs Xetrapal-MainThread-[save_profile] INFO : Saving own JSON profile to file /opt/sakhacabs-appdata/xetrapal-data/jeeva.json
> 2019-01-03 14:19:44 Sakha Cabs Xetrapal-MainThread-[<module>] ERROR : Error connecting to Google Drive, check connectivity - AttributeError("'NoneType' object has no attribute 'open_by_key'",) 'NoneType' object has no attribute 'open_by_key'
> 2019-01-03 14:19:44 Sakha Cabs Xetrapal-MainThread-[<module>] INFO : Setting up MongoEngine
>  * Serving Flask app "sakhacabs.api" (lazy loading)
>  * Environment: production
>    WARNING: Do not use the development server in a production environment.
>    Use a production WSGI server instead.
>  * Debug mode: off
>  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
> 127.0.0.1 - - [03/Jan/2019 14:20:11] "GET / HTTP/1.1" 404 -
> 127.0.0.1 - - [03/Jan/2019 14:20:11] "GET /favicon.ico HTTP/1.1" 404 -
> 127.0.0.1 - - [03/Jan/2019 14:20:20] "GET / HTTP/1.1" 404 -
> 127.0.0.1 - - [03/Jan/2019 14:20:20] "GET /favicon.ico HTTP/1.1" 404 -
> 127.0.0.1 - - [03/Jan/2019 14:20:37] "GET / HTTP/1.1" 404 -
> 

**Expected behavior**
Should open the app with index or home page

**Screenshots**
![image](https://user-images.githubusercontent.com/1178055/50629692-a5d6af80-0f63-11e9-8622-4e65378b0b4c.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox 64 (64 bit)
 - Version: Python 2.7.15rc1

**Comment by arjunvenkatraman** [comment]
Please take a look at https://github.com/hackergram/sakhacabs/blob/master/docs/TESTING_SAKHA_VPN.md
Substitute 10.8.0.8 with your server's IP address.

**Comment by suryaveer5320129** [comment]
I think you should run it  with:

 
http://192.168.0.126/sakhadispatcher/
