### ISSUE TITLE
[BUG]-Regression 1.01-Same booking is being created many times, by pressing save button many times 

### ISSUE THREAD

**Issue by suryaveer5320129** [hackergram/sakhacabs#257]
**Describe the bug**
Same booking is being created many times, by pressing save button many times .

**To Reproduce**
1. Go to 'create bookings'
2. Fill all the necessary 'inputs'
3. Click on 'save button multiple times '

**Comment by arjunvenkatraman** [comment]
Its not the same booking, every single booking has a unique value added in the cust meta, open the booking and check
