### ISSUE TITLE
[FR]- Add select for all multiple deletes.

### ISSUE THREAD

**Issue by karan100010** [hackergram/sakhacabs#259]
**Is your feature request related to a problem? Please describe.**
It should have the option for Select all for multiple deletes along with one by one selection 
because to select 100 bookings for deleting is not that feasible for the dispatcher .

**Comment by arjunvenkatraman** [comment]
This should be a simple function in Javascript datatables. (In fact even export is a function) Look at - https://stackoverflow.com/questions/42570465/datatables-select-all-checkbox

**Comment by arjunvenkatraman** [comment]
https://jsfiddle.net/annoyingmouse/yxLrLr8o/

**Comment by arjunvenkatraman** [comment]
Also, please fill templates out properly!!!!!
