### ISSUE TITLE
Dispatcher is not showing any error,  when there is no vehicle assigned to a driver 

### ISSUE THREAD

**Issue by suryaveer5320129** [hackergram/sakhacabs#26]
When I am clicking on a booking and I am assigning a duty slip to it, but the driver has not been assigned any vehicles, the dispatcher is still showing "resp" on the top of the screen as shown in the screenshot below. And not making any bookings, but also is not pointing  out that i have not assigned any vehicle to the driver. hence it is not able to take any bookings.
<img width="1280" alt="screen shot 2018-11-21 at 11 15 42 pm" src="https://user-images.githubusercontent.com/39553877/48860266-753d1b00-ede6-11e8-87fd-09d55871744f.png">

**Comment by arjunvenkatraman** [comment]
Related to https://github.com/hackergram/sakhacabs/issues/9
