### ISSUE TITLE
[BUG]-When clicking on "export" button multiple times the multiple files getting downloaded which is slowing the export process.

### ISSUE THREAD

**Issue by karan100010** [hackergram/sakhacabs#260]
**Describe the bug**

**To Reproduce**
1. Go to http://localhost/sakhacabs
2. Click on 'export button multiple times'
3. See error

**Expected behavior**
File should download multiple times 

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser :Mozilla Firefox 
 - Version Not specified

**Comment by arjunvenkatraman** [comment]
Please fill bug templates out properly!

**Comment by arjunvenkatraman** [comment]
Have added a loader for the exports, see if this improves exprerience

**Comment by arjunvenkatraman** [comment]
Closing for now, please re-open if the issue crops up. Should be addressed in the next maintenance release @karan100010
