### ISSUE TITLE
[FR]-Add "Extra hrs" and "Extra kms" in should be added in for importing products.

### ISSUE THREAD

**Issue by karan100010** [hackergram/sakhacabs#261]
**Is your feature request related to a problem? Please describe.**
There is no way if  Dispatcher want to add extra hours and extra kms in the booking sections so the import booking section should have the specific columns for extra hours and extra kms.

**Comment by arjunvenkatraman** [comment]
Please fill out the template properly!
UI = This should be simple enough, copy existing lines of code for existing fields and ensure that it is sent all the way along. 
Backend = Affects Invoicing WorkFlow, Product Edit Workflow and Booking workflow. To add issues for all these when we get there.

**Comment by arjunvenkatraman** [comment]
Working on this, backend to forward. 
1. Regression test Invoice and fix bugs
2. Add fields to document definition
3. Add validation for field
4. Make change in generate_invoice function
5. Test Generation of invoice with new model

**Comment by arjunvenkatraman** [comment]
UI Changes 
1. Add form fields
2. Add mapping workflow
3. Test generated data on API
4. Test notification on UI

**Comment by arjunvenkatraman** [comment]
@suryaveer5320129 Please pull staging and test
1. Delete all existing products
2. Import new products
    1. Specify the extra hours rate column
    2. Specify the extra kms rate column
3. Import the products
4. Ensure that they are shown correctly in the table
5. Create a new booking with one of the new products
6. Assign the booking to a driver
7. Open -> close duty slip as a driver would (with some kms and some checkin and checkout time. 
8. Close the assignment
9. Create an invoice with the assignment
10. Ensure that correct amount is generated in the invoice. 


Caveats - In the case of multiple products assigned to the same assignment, max rate will be chosen.

**Comment by suryaveer5320129** [comment]
checked, and is working fine
