### ISSUE TITLE
[FR]-Errors are not correctly describing problems with the entries, it should be more accurate 

### ISSUE THREAD

**Issue by suryaveer5320129** [hackergram/sakhacabs#266]
Errors should be more accurate and should have some more information contained.

**Comment by arjunvenkatraman** [comment]
@suryaveer5320129 Please list each error separately.
@karan100010 - 
General method to fix - 
1. Generate a sample input dataset that reliably generates the error we want to fix
2. Find the point in the UI where the input dataset is converted to a format that the API can consume.
3. Add logging to dump the data actually being sent to the API
4. Using the dumped data, ensure that the API (And backend where necessary) is returning the correct error message
5. Identify the location the UI code where user response is being displayed.
6. Alter code to ensure that error is displayed
    1. For single line text use a Javascript alert
    2. For tabular text (as in a failed import) - show the output in a datatable.

**Comment by arjunvenkatraman** [comment]
Consider using https://notifyjs.jpillora.com/

**Comment by suryaveer5320129** [comment]
jkbkb

**Comment by arjunvenkatraman** [comment]
CLosing provisionally, add new issues for each poorly reported error @suryaveer5320129
