### ISSUE TITLE
[BUG]-Regression 1.01- Cancelled assignments should not be allowed to invoiced

### ISSUE THREAD

**Issue by suryaveer5320129** [hackergram/sakhacabs#269]
**Describe the bug**
System can generate the invoices of the cancelled assignments, which needs to be fixed.

**To Reproduce**
1. Go to 'manage invoices'
2. Click on 'check box on a invoice which is cancelled '

**Expected behavior**

**Desktop (please complete the following information):**
 - O.S. Ubuntu 18.04 Bionic beaver
 - Browser [Firefox]
 - Version [Mozilla Firefox 64.0]

**Comment by arjunvenkatraman** [comment]
Confirm with RItesh ji if this is needed, re-open if so.
