### ISSUE TITLE
Telegram-bot is not responding

### ISSUE THREAD

**Issue by suryaveer5320129** [hackergram/sakhacabs#27]
When an assignment with multiple drivers and one trip was tested the telegram-bot stops responding after I clicked on the duty slip.
![image](https://user-images.githubusercontent.com/39553877/48861832-91db5200-edea-11e8-9d52-ad98b8caddee.png)

**Comment by arjunvenkatraman** [comment]
No further info. Blaming on Internet connectivity and moving on, but should watch for repeats.
