### ISSUE TITLE
[BUG]-Regression 1.01-Unable to add assignment to invoice. 

### ISSUE THREAD

**Issue by suryaveer5320129** [hackergram/sakhacabs#274]
**Describe the bug**
When a dispatcher try to add a assignment to a invoice it comes with a error.
**To Reproduce**
1. Go to 'manage invoices'
2. Click on 'add invoice check box'
3. See error
172.20.10.2 - - [06/Jan/2019 17:06:33] "OPTIONS /invoice/generateinvoice HTTP/1.1" 200 -
2019-01-06 17:06:33 Sakha Cabs Xetrapal-Thread-35-[post] INFO : [u'5c31b8bbffdc810897d81014']
2019-01-06 17:06:33 Sakha Cabs Xetrapal-Thread-35-[post] INFO : Trying to generate invoice
2019-01-06 17:06:33 Sakha Cabs Xetrapal-Thread-35-[post] INFO : [<Assignment: 
    status = u'open',
    reporting_timestamp = 2019-01-30 08:10:09,
    drop_location = u'0-',
    reporting_location = u'Delhi-dsa',
    bookings = [<Booking: 
    status = u'open',
    drop_location = u'0-',
    product_id = u'SINGLTRP',
    num_passengers = None,
    assignment = u'5c31b8bbffdc810897d81014',
    id = ObjectId('5c31b801ffdc810897d81012'),
    passenger_mobile = u'918368988155',
    passenger_detail = u'cola candy 918368988155 sadajdgbaguyvas',
    booking_id = u'190106x6uv',
    cust_meta = {u'unique': u'2019-01-06 13:40:40'},
    cust_id = u'retail',
    created_timestamp = 2019-01-06 08:10:41,
    remarks = None,
    pickup_location = u'Delhi-dsa',
    booking_channel = u'webform',
    notification_prefs = {u'assigned': [u'+918368988155'], u'new': [u'', u'+918368988155'], u'cancelled': [u'', u'+918368988155'], u'open': [u'+918368988155'], u'closed': [u'+918368988155']},
    pickup_timestamp = 2019-01-30 08:10:09,
>],
    cust_id = u'retail',
    created_timestamp = 2019-01-06 08:13:47,
    id = ObjectId('5c31b8bbffdc810897d81014'),
>]
2019-01-06 17:06:33 Sakha Cabs Xetrapal-Thread-35-[generate_invoice] INFO : Generating invoice for assignments [<Assignment: 
    status = u'open',
    reporting_timestamp = 2019-01-30 08:10:09,
    drop_location = u'0-',
    reporting_location = u'Delhi-dsa',
    bookings = [<Booking: 
    status = u'open',
    drop_location = u'0-',
    product_id = u'SINGLTRP',
    num_passengers = None,
    assignment = u'5c31b8bbffdc810897d81014',
    id = ObjectId('5c31b801ffdc810897d81012'),
    passenger_mobile = u'918368988155',
    passenger_detail = u'cola candy 918368988155 sadajdgbaguyvas',
    booking_id = u'190106x6uv',
    cust_meta = {u'unique': u'2019-01-06 13:40:40'},
    cust_id = u'retail',
    created_timestamp = 2019-01-06 08:10:41,
    remarks = None,
    pickup_location = u'Delhi-dsa',
    booking_channel = u'webform',
    notification_prefs = {u'assigned': [u'+918368988155'], u'new': [u'', u'+918368988155'], u'cancelled': [u'', u'+918368988155'], u'open': [u'+918368988155'], u'closed': [u'+918368988155']},
    pickup_timestamp = 2019-01-30 08:10:09,
>],
    cust_id = u'retail',
    created_timestamp = 2019-01-06 08:13:47,
    id = ObjectId('5c31b8bbffdc810897d81014'),
>]
2019-01-06 17:06:33 Sakha Cabs Xetrapal-Thread-35-[generate_invoice] ERROR : <type 'exceptions.IndexError'> no such item for Cursor instance
172.20.10.2 - - [06/Jan/2019 17:06:33] "POST /invoice/generateinvoice HTTP/1.1" 200 -
172.20.10.2 - - [06/Jan/2019 17:06:42] "GET /invoice?_=1546774540023 HTTP/1.1" 200 -

**Expected behavior**
It should add the assignment to the invoice.

**Desktop (please complete the following information):**
 - OS: [Linux, Ubuntu 18.04]
 - Browser [Firefox]
 - Version [Mozilla Firefox 64.0]

**Comment by arjunvenkatraman** [comment]
Please provide the full error trace, including the preceding lines

**Comment by arjunvenkatraman** [comment]
Is this fixed now @suryaveer5320129
