### ISSUE TITLE
[FR]-REFACTOR-Move all Javascript into JS files and refactor links in all files to update

### ISSUE THREAD

**Issue by arjunvenkatraman** [hackergram/sakhacabs#276]
**Is your feature request related to a problem? Please describe.**
CODE REFACTOR

**Describe the solution you'd like**
1. Invoice Related Functions
2. Check all manage pages. 
**Describe alternatives you've considered**

**Additional context**

**Comment by suryaveer5320129** [comment]
duplicate of #318
