### ISSUE TITLE
[BUG]-Regression 1.01- Dispatcher UI is giving unknown error when is opened in google chrome.

### ISSUE THREAD

**Issue by suryaveer5320129** [hackergram/sakhacabs#279]
**Describe the bug**
When the Dispatcher UI is opened in google chrome, it took a long time to load firstly and then browser console came with the Error

**To Reproduce**
1. Go to 'google chrome'
2. Click on 'localhost/sakhadispatcher'
3. Open the 'browser console'
`material-dashboard.js:420 Uncaught TypeError: Cannot read property 'outerHTML' of undefined
    at Object.<anonymous> (material-dashboard.js:420)
    at material-dashboard.js:513`

**Desktop (please complete the following information):**
 - OS: [Linux, Ubuntu 18.04 BIonic beaver]
 - Browser [google chrome]

**Comment by arjunvenkatraman** [comment]
This error does not seem to cause any issue to the UI on Ubuntu 18.04. I am able to interact with dispatcher correctly and most functions seem to work at least at first check.  Please file individual issues for specific issues that occur.
