### ISSUE TITLE
[FAQ]-AttributeError: 'Xetrapal' object has no attribute 'get_sms_astra'

### ISSUE THREAD

**Issue by kirantpatil** [hackergram/sakhacabs#280]
**Describe the bug**
I updated to latest master and did once again "pip install requirement.txt " and executed sudo python dispatcherapi.py which is resulting in below error.

I noticed that INSTALL.md the following line is incorrect and pointing to directory that does not exist
sudo ln -s /opt/sakhacabs/sakhadispatcher /var/www/html/sakhadispatcher

It should be "sudo ln -s /opt/sakhacabs/dispatcher /var/www/html/sakhadispatcher"

**To Reproduce**
1. git pull 
2. sudo pip install -r requirements.txt
3. sudo python dispatcherapi.py

>     $ sudo python dispatcherapi.py
> 2019-01-06 19:16:18 Sakha Cabs Xetrapal-MainThread-[__init__] INFO : My name is Sakha Cabs Xetrapal
> 2019-01-06 19:16:18 Sakha Cabs Xetrapal-MainThread-[setup_disk] INFO : I already have a datapath at the location /opt/sakhacabs-appdata/xetrapal-data
> 2019-01-06 19:16:18 Sakha Cabs Xetrapal-MainThread-[start_session] INFO : Creating a new path for this session at /opt/sakhacabs-appdata/xetrapal-data/XpalSession-2019Jan06-191618
> 2019-01-06 19:16:18 Sakha Cabs Xetrapal-MainThread-[start_session] INFO : Creating a new download path for this session at /opt/sakhacabs-appdata/xetrapal-data/XpalSession-2019Jan06-191618/downloads
> 2019-01-06 19:16:18 Sakha Cabs Xetrapal-MainThread-[start_session] INFO : Creating a new json path for this session at /opt/sakhacabs-appdata/xetrapal-data/XpalSession-2019Jan06-191618/json 
> 2019-01-06 19:16:18 Sakha Cabs Xetrapal-MainThread-[log_to_disk] INFO : Saving messages to log at /opt/sakhacabs-appdata/xetrapal-data/XpalSession-2019Jan06-191618/jeevasession.log
> 2019-01-06 19:16:18 Sakha Cabs Xetrapal-MainThread-[save_profile] INFO : Saving own JSON profile to file /opt/sakhacabs-appdata/xetrapal-data/jeeva.json
> 2019-01-06 19:16:18 Sakha Cabs Xetrapal-MainThread-[update_astras] INFO : Trying to update astras
> 2019-01-06 19:16:18 Sakha Cabs Xetrapal-MainThread-[update_astras] WARNING : I dont seem to have any astras
> 2019-01-06 19:16:18 Sakha Cabs Xetrapal-MainThread-[save_profile] INFO : Saving own JSON profile to file /opt/sakhacabs-appdata/xetrapal-data/jeeva.json
> 2019-01-06 19:16:18 Sakha Cabs Xetrapal-MainThread-[update_vaahans] INFO : Trying to update vaahans
> 2019-01-06 19:16:18 Sakha Cabs Xetrapal-MainThread-[update_vaahans] WARNING : I dont seem to have any vaahans
> 2019-01-06 19:16:18 Sakha Cabs Xetrapal-MainThread-[save_profile] INFO : Saving own JSON profile to file /opt/sakhacabs-appdata/xetrapal-data/jeeva.json
> 2019-01-06 19:16:19 Sakha Cabs Xetrapal-MainThread-[save_profile] INFO : Saving own JSON profile to file /opt/sakhacabs-appdata/xetrapal-data/jeeva.json
> 2019-01-06 19:16:19 Sakha Cabs Xetrapal-MainThread-[get_googledriver] INFO : Trying to log into Google drive
> 2019-01-06 19:16:19 Sakha Cabs Xetrapal-MainThread-[get_googledriver] ERROR : Could not get google driver config because [Errno 2] Client secret file does not exist.: u'/opt/sakhacabs-appdata/xetrapal-auth/sakhacabsxpal.json'
> 2019-01-06 19:16:19 Sakha Cabs Xetrapal-MainThread-[update_astras] INFO : Trying to update astras
> 2019-01-06 19:16:19 Sakha Cabs Xetrapal-MainThread-[save_profile] INFO : Saving own JSON profile to file /opt/sakhacabs-appdata/xetrapal-data/jeeva.json
> Traceback (most recent call last):
>   File "dispatcherapi.py", line 8, in <module>
>     from sakhacabs.api import *
>   File "/home/smitha/Documents/kiran/sakhacabs/sakhacabs/api.py", line 16, in <module>
>     from sakhacabs import xpal
>   File "/home/smitha/Documents/kiran/sakhacabs/sakhacabs/xpal.py", line 22, in <module>
>     sms = sakhacabsxpal.get_sms_astra()
> AttributeError: 'Xetrapal' object has no attribute 'get_sms_astra'
> 

**Expected behavior**
It should start sakhadispatcher service/server.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox 64
 - Version: Python 2.7.15rc1

**Comment by kirantpatil** [comment]
Also noticed that the below line has issue.

/opt/sakhacabs-appdata in place of /home/arjun/sakhacabs

I have changed that line as below.
```
    "datapath": "/home/smitha/Documents/kiran/sakhacabs/xetrapal-data",
    "jeevajsonfile": "/home/smitha/Documents/kiran/sakhacabs/xetrapal-data/jeeva.json",
```
But "/home/smitha/Documents/kiran/sakhacabs" directory doesn't have "xetrapal-data" directory in it.

xetrapal-data directory is found in "/opt/sakhacabs-appdata".

Please clarify and update the INSTALL doc.

**Comment by arjunvenkatraman** [comment]
@suryaveer5320129  please fix the INSTALL.md 
Also, please provide @kirantpatil  with the config update for the SMS set up.
The feature allows an SMS notification to be sent as per the user's preference at the time of creating the booking.

**Comment by arjunvenkatraman** [comment]
Error is non blocking and can be ignored for the initial phase.
