### ISSUE TITLE
[Test Case] Check that DutySlip edits from the Dispatcher interface save the correct timezone

### ISSUE THREAD

**Issue by arjunvenkatraman** [hackergram/sakhacabs#281]
1. Create an assignment
2. Open the duty slip from the dispatcher. 
3. Set the open time as "YYYY-MM-DD HH:MM:SS" format
4. Set the close time as "YYYY-MM-DD HH:MM:SS" format
5. Save the dutyslip

Ensure
1. The timezone is not getting messed up on save
2. Validations that apply in the case of regular dutyslip edits (open/close time and kms) are maintained while editing from the dispatcher as well.

**Comment by arjunvenkatraman** [comment]
Should be fixed, @suryaveer5320129  pls test in staging

**Comment by suryaveer5320129** [comment]
Checked and is working fine on production server
