### ISSUE TITLE
[BUG]-Regression 1.01- Save Dutyslip should raise an error if obviously incorrect input is provided

### ISSUE THREAD

**Issue by suryaveer5320129** [hackergram/sakhacabs#286]
**Describe the bug**

**To Reproduce**
System should check if the:
1. Vehicles is valid
2. Open time stamp should not be less than close time stamp
3. Open kilometers should not be less than close kilometers
![image](https://user-images.githubusercontent.com/39553877/50741039-17418700-121e-11e9-9056-f61dd2793cf5.png)

**Comment by suryaveer5320129** [comment]
It is duplicate of #285

**Comment by arjunvenkatraman** [comment]
Fixed, @suryaveer5320129  please test in staging
Also, please verify that the timezone issue has not cropped up again #289 #285
