### ISSUE TITLE
[BUG]-Regression 1.01- Driver Id in the edit duty slip form must be a read only entity.

### ISSUE THREAD

**Issue by suryaveer5320129** [hackergram/sakhacabs#290]
**Describe the bug**
In the edit duty slip form dispatcher had the option to edit the Driver ID, which must not be edited by the dispatcher through edit duty slip because driver id is a primary key for the driver.

**Comment by arjunvenkatraman** [comment]
Fixed, @suryaveer5320129  pls test in staging

**Comment by arjunvenkatraman** [comment]
This should be closed, closing, @suryaveer5320129 pls reopen if the problem comes back
