### ISSUE TITLE
[BUG]-Regression 1.01- Unable to edit DutySlip in google chrome

### ISSUE THREAD

**Issue by suryaveer5320129** [hackergram/sakhacabs#295]
**Describe the bug**
When Dispatcher tries to enter duty slip in google chrome, it is not saving after editing 

**To Reproduce**
1. Go to 'edit duty slip'
2. Click on 'success'
4. Check the error 

**Expected behavior**
It should save the duty slip after editing.

**Desktop (please complete the following information):**
 - OS: [Linux, Ubuntu 18.04]
 - Browser [chrome]
 - Version [not specified]

**Comment by arjunvenkatraman** [comment]
This is working correctly as of now, open again if fails (tested linux, windows to be verified)
