### ISSUE TITLE
[BUG]-V1.01 Feedback Regression Testing- Pickup timestamp is not setting up correctly while importing bookings.

### ISSUE THREAD

**Issue by suryaveer5320129** [hackergram/sakhacabs#300]
**Describe the bug**
Pickup timestamp is not setting up correctly while importing bookings 

**See errors**
`
"status": "<class 'mongoengine.errors.ValidationError'> ValidationError (Booking:None) (Field is required: ['pickup_timestamp'])"
`
 I have entered {{Booking date}} and {{Reporting time}}  whose values are equal to 2018-12-11 and 18:30

**Expected behavior**
It should import the bookings

**Desktop (please complete the following information):**
NA

**Comment by suryaveer5320129** [comment]
again pickup time stamp is giving some error:
this is the preview of the booking data 
{
"booking date": "2018-10-10T00:00:00.000Z",
"client name": "cattie",
"drop": "store",
"mobile": 123456789101,
"pickup": "office",
"reporting time": 0.638912037037037,
"status": "<class 'mongoengine.errors.ValidationError'> ValidationError (Booking:None) (cannot parse date \"Invalid date\": ['pickup_timestamp'])"
}

**Comment by arjunvenkatraman** [comment]
New formats may continue to raise errors. We need to identify the set of files that will be common immediately after go-live and support those while continuing to file issues for specific files that fail (such as #317)

**Comment by suryaveer5320129** [comment]
Pickup timestamp is showing invalid date when date is in yyyy-mm-hh and time format in in hh:mm while importing the file of gadventures

**Comment by suryaveer5320129** [comment]
tested and is working fine
