### ISSUE TITLE
[BUG]-V1.01 Feedback Regression Testing- Unable to process a larger file on importing bookings  

### ISSUE THREAD

**Issue by suryaveer5320129** [hackergram/sakhacabs#303]
**Describe the bug**
Dispatcher is not able to import a file of 4000 bookings, and the system is not showing any error and got hangs along with the browser freezing

**To Reproduce**
1. Go to 'manage bookings'
2  Import the file which is having  4000 bookings and See error

**Expected behavior**
Either it should process and import the data or else it should the loading confirmation if the system can process and import the data if not, the system should show the error and the cancel button 

**Desktop (please complete the following information):**
 - OS: [Linux, Ubuntu 18.04 Bionic Beaver]
 - Browser [Firefox]
 - Version [Version64]

**Comment by karan100010** [comment]
I am using https://github.com/SheetJS/SheetJS.github.io/issues/12 as a reference to fix this issue. I have uploaded the file you used for the issue  in http://oss.sheetjs.com/js-xlsx/ . Will see what we have done differently from them.

**Comment by arjunvenkatraman** [comment]
Tested with 4000 record file on two dev systems. It appears to be an issue isolated to the testing system. Please test again after closing unnecessary extra tabs and programs to see if your system is overloaded from another source. 
Also, are you possibly testing this from inside a VM? In that case the VM might need more resources. Please consider and reopen if needed.
