### ISSUE TITLE
Telegram-bot not responding after entering alphabets  

### ISSUE THREAD

**Issue by suryaveer5320129** [hackergram/sakhacabs#31]
Telegram bot is not responding after entering alphabets in the place of numbers in "Open Kms"

![image](https://user-images.githubusercontent.com/39553877/48956910-92efb900-ef7b-11e8-8fab-31533b623a78.png)
![image](https://user-images.githubusercontent.com/39553877/48956914-96834000-ef7b-11e8-8cc9-112d53a26c18.png)

**Comment by arjunvenkatraman** [comment]
Please replace images with properly anonymized ones
