### ISSUE TITLE
[BUG]-V1.01 Feedback Regression Testing- Dispatcher can take only some files for booking.

### ISSUE THREAD

**Issue by suryaveer5320129** [hackergram/sakhacabs#310]
**Describe the bug**
While importing bookings dispatcher is only taking some files successfully in other files, it is showing error in importing 

**Screenshots**
Na

**Desktop (please complete the following information):**
 NA

**Smartphone (please complete the following information):**
na

**Additional context**
na

**Comment by arjunvenkatraman** [comment]
Pls pull staging and retest @suryaveer5320129

**Comment by suryaveer5320129** [comment]
Closing for now, if it is persistant, will reopen
