### ISSUE TITLE
[BUG]-V1.01 Feedback Regression Testing- Unable to import some booking files in dispatcher 

### ISSUE THREAD

**Issue by suryaveer5320129** [hackergram/sakhacabs#311]
**Describe the bug**
Unable to upload some  booking files on dispatcher 

 See error
`Error: Script terminated by timeout at:
make_json_row@https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.14.1/xlsx.js:20489:45
sheet_to_json@https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.14.1/xlsx.js:20556:13
to_json/<@http://192.168.43.222/sakhadispatcher/managebookings.html:494:14
to_json@http://192.168.43.222/sakhadispatcher/managebookings.html:493:3
process_wb@http://192.168.43.222/sakhadispatcher/managebookings.html:554:22
do_file/reader.onload@http://192.168.43.222/sakhadispatcher/managebookings.html:622:9
xlsx.js:20489:45
`

**Expected behavior**
it should import the booking

**Screenshots**
na

**Desktop (please complete the following information):**
 - na

**Smartphone (please complete the following information):**
na

**Additional context**
na

**Comment by arjunvenkatraman** [comment]
Identical to #316
