### ISSUE TITLE
[Question]-Unable to configure apache2  server

### ISSUE THREAD

**Issue by Mallikarjun-biradar** [hackergram/sakhacabs#312]
unable to configure apache,it could be very helpfull to add apache config file and installation step.

[
![terminal](https://user-images.githubusercontent.com/46191804/50984732-8bcf3b00-1528-11e9-8242-96946d6dfabd.png)

![url not_found](https://user-images.githubusercontent.com/46191804/50984733-8c67d180-1528-11e9-9773-47d417ce201a.png)

]

**Comment by arjunvenkatraman** [comment]
You would need to link the dispatcher into the apache HTML directory

```
sudo ln -s /opt/sakhacabs/dispatcher /var/www/html/sakhadispatcher
sudo ln -s /opt/sakhacabs/bookingweb /var/www/html/bookingweb

```

After this you should be able to open the page in http://<ipaddress>/sakhadispatcher
@suryaveer5320129  I think our installation process is missing the softlinks in the web server, that needs to get added
