### ISSUE TITLE
[FR]-Importing should have delete current page button 

### ISSUE THREAD

**Issue by vinaytaragi** [hackergram/sakhacabs#314]
**Is your feature request related to a problem? Please describe.**
Disptacher should have a delete current page in manage section 

**Describe the solution you'd like**
it should have the delete current page button in manage section

**Describe alternatives you've considered**
na

**Additional context**
na

**Comment by karan100010** [comment]
http://live.datatables.net/wixutixi/19/edit found a solution here.
