### ISSUE TITLE
[FR]-[CRITICAL]- Add two fields "Vehicle Category" and "Vehicle name" in Manage Vehicle section

### ISSUE THREAD

**Issue by suryaveer5320129** [hackergram/sakhacabs#315]
**Is your feature request related to a problem? Please describe.**
It should have two more input forms in manage bookings, for dispatcher's ease

**Describe the solution you'd like**
Two more fields in manage bookings

**Describe alternatives you've considered**
na

**Additional context**
na

**Comment by karan100010** [comment]
all done except data loding check "fillVehiclesmodal" function please check the function.

**Comment by suryaveer5320129** [comment]
Checked and is working fine
