### ISSUE TITLE
[BUG]-V1.02 Maintenance Release- There should be the proper validation of the size of the product ID

### ISSUE THREAD

**Issue by suryaveer5320129** [hackergram/sakhacabs#327]
**Describe the bug**
Dispatcher can import a product from a excel file in which Product id is having less than 5 characters, but when dispatcher tries to edit any field in any product, system throws a error that "product ID must be at least 5 characters"

**To Reproduce**
1. Go to 'import products' and import a file which is having product Id of invalid length.
2. Edit any of the product and check the error.

**Expected behavior**
I want that dispatcher should throw an error if the product ID in the file which is to be iimported is of invalid length/character/type

**Screenshots**
na

**Desktop (please complete the following information):**
 na

**Smartphone (please complete the following information):**
na

**Additional context**

**Comment by arjunvenkatraman** [comment]
Set to five, should be fixed in both single and bulk creates. @suryaveer5320129 , reopen if necessary
