### ISSUE TITLE
Bot not responding after entring spacial charecters in "duty slip number"

### ISSUE THREAD

**Issue by karan100010** [hackergram/sakhacabs#33]
Will update screenshot in the morning

**Comment by suryaveer5320129** [comment]
![image](https://user-images.githubusercontent.com/39553877/48975648-c295e280-f09b-11e8-976e-f2efa3a354b3.png)

**Comment by arjunvenkatraman** [comment]
Did you try responding with "done" or "Done"?
that should reset
If it does not, will fix.

**Comment by suryaveer5320129** [comment]
![image](https://user-images.githubusercontent.com/39553877/48999783-ac605300-f17d-11e8-9d9e-de667b2873e4.png)
