### ISSUE TITLE
[FR]-V1.02 Maintenance Release- Error still needs to be more accurate from the user's point.

### ISSUE THREAD

**Issue by suryaveer5320129** [hackergram/sakhacabs#334]
**Is your feature request related to a problem? Please describe.**
Errors are still lacking in information.

**Describe the solution you'd like**
Errors should be more accurate from the user's point of view and it should also have the information of the item/datapoint which are invalid/unknown or which contains issues/bugs in them

**Describe alternatives you've considered**
na

**Additional context**
Errors should be in such a way that the person, who will be the dispatcher (considering to be non-techie) shall understand the problem

**Comment by arjunvenkatraman** [comment]
Please file separate issues for each instance where error is unclear @suryaveer5320129
