### ISSUE TITLE
[BUG]- V1.02 Maintenance Release - Edit Booking form should ignore the error of special character while editing a booking 

### ISSUE THREAD

**Issue by suryaveer5320129** [hackergram/sakhacabs#337]
**Describe the bug**
When dispatcher tries to edit the booking in manage booking section, it shows a special character error in passenger details, but while importing there is no such error. so this error message should be fixed 

**To Reproduce**
1. Go to 'manage bookings'
2. Click on 'bookings edit form '
3. make any changes and see the error 
`Caught Error saving booking - passenger_detail - has special character <_sre.SRE_Match object at 0x7fe23bf887e8>`

**Expected behavior**
It should not show any error while edit a imported booking

**Screenshots**
na

**Desktop (please complete the following information):**
na

**Smartphone (please complete the following information):**
na

**Additional context**
na

**Comment by arjunvenkatraman** [comment]
. , and / have been allowed and tested with postman. Please confirm from UI and close @suryaveer5320129

**Comment by suryaveer5320129** [comment]
it should also have the colons :  and braces () contained

**Comment by arjunvenkatraman** [comment]
Tested closed, reopen if issue. Please create a test case in Postman for this @suryaveer5320129
