### ISSUE TITLE
[FR]-V1.02 Maintenance Release-There should be a modal for edit vehicle ID in vehicle status in index page of Dispatcher interface

### ISSUE THREAD

**Issue by suryaveer5320129** [hackergram/sakhacabs#345]
**Is your feature request related to a problem? Please describe.**
There should be a modal for edit vehicle ID in vehicle status in index page of Dispatcher interface

**Describe the solution you'd like**
There is no modal in the index page for vehicles in dispatcher interface.

**Describe alternatives you've considered**
na

**Additional context**
na

**Comment by arjunvenkatraman** [comment]
Edit vehicle is already available in manage vehicles. Will add this in a later release.

**Comment by suryaveer5320129** [comment]
Modal has been added in the dispatcher main interface in vehicle status field but the modal is not opening the contents
