### ISSUE TITLE
[BUG]-V1.02 Maintenance Release- The formatting of the template fields in the manage products section needs to be normalised 

### ISSUE THREAD

**Issue by suryaveer5320129** [hackergram/sakhacabs#347]
**Describe the bug**
The formatting of the template fields in the manage products section should be normalised 

**To Reproduce**
na

**Expected behavior**
na

**Screenshots**
![image](https://user-images.githubusercontent.com/39553877/51424740-3fef5680-1bf8-11e9-8603-75c333817a53.png)

**Desktop (please complete the following information):**
na

**Smartphone (please complete the following information):**
 na

**Additional context**
na

**Comment by arjunvenkatraman** [comment]
![image](https://user-images.githubusercontent.com/743783/51431263-63dc8780-1c4c-11e9-842e-8a4950d71616.png)

**Comment by suryaveer5320129** [comment]
![image](https://user-images.githubusercontent.com/39553877/51440027-21688880-1ce8-11e9-8555-ea344fc7c7b8.png)
