### ISSUE TITLE
[BUG]-V1.02 Maintenance Release- Dispatcher is deleting all the drivers rather than deleting the drivers of the current page 

### ISSUE THREAD

**Issue by suryaveer5320129** [hackergram/sakhacabs#351]
**Describe the bug**
Dispatcher is deleting all the drivers rather than deleting the drivers of the page 

**To Reproduce**
1. Go to 'manage drivers'
2. Click on 'delete '

**Expected behavior**
it should only delete the drivers of a particular page 

**Screenshots**
na

**Desktop (please complete the following information):**
na

**Smartphone (please complete the following information):**
na

**Additional context**
na

**Comment by arjunvenkatraman** [comment]
tested closed, re-open if needed
