### ISSUE TITLE
[BUG]-v1.02-Search invoice is not working.

### ISSUE THREAD

**Issue by karan100010** [hackergram/sakhacabs#366]
**Describe the bug**

**To Reproduce**
1. Go to 'manage invoice'
2. Select dates and Click on "Search ''
3. Scroll down to 'console log'

**Expected behavior**
A clear and concise description of what you expected to happen.The page should display the invoices it has found to the corresponding dates/

**Screenshots**
<img width="1280" alt="screen shot 2019-02-16 at 2 10 51 pm" src="https://user-images.githubusercontent.com/36842700/52897050-afeffd00-31f5-11e9-888b-92dc308f3b6c.png">

**Desktop (please complete the following information):**
 - OS: Mac OS 
 - Browser Firefox developers edition 
 - Version 3.3

**Smartphone (please complete the following information):**

**Additional context**

**Comment by suryaveer5320129** [comment]
tested and is working fine on local system
