### ISSUE TITLE
Was able to fill numbers and spacial "passenger detail" column

### ISSUE THREAD

**Issue by karan100010** [hackergram/sakhacabs#46]
<img width="1280" alt="screen shot 2018-12-03 at 1 45 05 pm" src="https://user-images.githubusercontent.com/36842700/49361443-1179f280-f702-11e8-9eb0-83b336aebc6f.png">

**Comment by arjunvenkatraman** [comment]
Please add a screenshot of the booking as created in the bookings pane.
