### ISSUE TITLE
Able to enter a random number in 'phone number' column.

### ISSUE THREAD

**Issue by karan100010** [hackergram/sakhacabs#48]
<img width="1280" alt="screen shot 2018-12-03 at 1 54 46 pm" src="https://user-images.githubusercontent.com/36842700/49361898-286d1480-f703-11e8-9499-d5bb30558158.png">

**Comment by arjunvenkatraman** [comment]
Please add a screenshot of the booking as created in the bookings pane.

**Comment by arjunvenkatraman** [comment]
Should cap at 12 digits including 91, which should be added by default (actually should have a country code field separate etc)
