### ISSUE TITLE
Able to enter number and spacial characters under "pickup location"

### ISSUE THREAD

**Issue by karan100010** [hackergram/sakhacabs#49]
<img width="1280" alt="screen shot 2018-12-03 at 2 09 04 pm" src="https://user-images.githubusercontent.com/36842700/49362624-3de33e00-f705-11e8-8472-1fcd6cc8f8d4.png">

**Comment by arjunvenkatraman** [comment]
Please add a screenshot of the booking as created in the bookings pane.
