### ISSUE TITLE
booking not going name not showing.

### ISSUE THREAD

**Issue by karan100010** [hackergram/sakhacabs#58]
![whatsapp image 2018-12-04 at 8 37 47 pm](https://user-images.githubusercontent.com/36842700/49452874-03ae9500-f808-11e8-9d59-b76b699f175b.jpeg)
![whatsapp image 2018-12-04 at 7 34 29 pm](https://user-images.githubusercontent.com/36842700/49452938-280a7180-f808-11e8-84c0-93d022cc2bfc.jpeg)
![whatsapp image 2018-12-04 at 7 34 30 pm](https://user-images.githubusercontent.com/36842700/49452939-280a7180-f808-11e8-8dae-8a60f376d1a7.jpeg)

![whatsapp image 2018-12-04 at 7 34 31 pm](https://user-images.githubusercontent.com/36842700/49452944-293b9e80-f808-11e8-8308-3ca6595c583d.jpeg)

**Comment by arjunvenkatraman** [comment]
Please replicate after latest updates

**Comment by arjunvenkatraman** [comment]
To clear the driver bot queue and start from scratch - 
Send - "done"
Send "/start"
