### ISSUE TITLE
[FAQ] Setup guide for testing/development

### ISSUE THREAD

**Issue by kirantpatil** [hackergram/sakhacabs#6]
Hi @arjunvenkatraman,

Could you please provide Setup guide for development/testing purpose ?

Thanks.

**Comment by arjunvenkatraman** [comment]
Thanks for opening the issue, will provide one asap.

**Comment by kirantpatil** [comment]
Thanks I will go through it and provide feedback for any improvement.

**Comment by kirantpatil** [comment]
Hi, Is there contribution guideline for fresher's to contribute to this project ? So that we can contribute to this project.

**Comment by kirantpatil** [comment]
I mean source code contribution by fixing existing bugs and working on enhancements/Feature requests. You can mark specific issues as "Beginner", "Advanced" ...

**Comment by arjunvenkatraman** [comment]
@kirantpatil  please see the INSTALL.md on the staging branch (will merge into master shortly) for installation instructions. If you would like to contribute, we would be very happy for help. Please send an email to mojoarjun at gmail dot com and will be happy to share basics!
