### ISSUE TITLE
Keyboard not switching to "number keyboard" when the bot is asking for a number.

### ISSUE THREAD

**Issue by karan100010** [hackergram/sakhacabs#61]
<img width="376" alt="screen shot 2018-12-05 at 12 44 54 pm" src="https://user-images.githubusercontent.com/36842700/49496369-c855aa00-f88b-11e8-8140-607150760a35.png">

**Comment by arjunvenkatraman** [comment]
Not do-able since telegram bot does not have a numerical keyboard option. Please file an issue for this with https://github.com/python-telegram-bot/python-telegram-bot and if they have a solution please let me know as well.
